[build]
  command = "yarn build"
  publish = "./public"


# TODO: убрать после забвения поисковиками
[[redirects]]
  from = "/posts/2023-11-26-vygodno-li-platit-kartoj-mir-pri-poezdkah-v-belarus"
  to = "/posts/2023-11-26-vygodno-li-platit-kartoj-mir-pri-poezdkah-v-belorussiyu"
