name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy-preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: |
            .cache
            public
            .netlify
          key: build-cache
      - name: deploy to preview mode
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
        run: |
          yarn --frozen-lockfile
          yarn deploy-preview
