name: 'Netlify Production Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy Production'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: |
            .cache
            public
          key: gatsby-cache
      - name: deploy to preview mode
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
        run: |
          yarn --frozen-lockfile
          yarn deploy
